### ISSUE TITLE
Add node v20 (iron) image

### ISSUE THREAD

**Issue by kxc-waddlaw** [kxcinc/pubinfra.dockerfiles#41]
Currently there are "hydrogen" (v18.0) and "latest" (v?) tags.
Please add the tag "iron" (v20.0).

**Comment by kxc-wraikny** [comment]
`nvm ls-remote` しても `iron` は出てこない。

**Comment by haochenx** [comment]
v20 はまだ LTS codename つけられてないですね..

@kxc-waddlaw latest として使うのが望ましくなかったりしますか

**Comment by kxc-waddlaw** [comment]
@kxc-wraikny 
20.x の Active LTS Start は 2023-10-24 らしい。
https://github.com/nodejs/release#release-schedule

-----

アルファベット順になっているんだ。知らなかった。

> Argon (4.x 2015)
Boron (6.x 2016)
Carbon (8.x 2017)
Dubnium (10.x 2018)
Erbium (12.x 2019)
Fermium (14.x 2020)
Gallium (16.x 2021)
Hydrogen (18.x 2022)
Iron (20.x 2023)
Jod (22.x 2024)

https://github.com/nodejs/Release/blob/main/CODENAMES.md

----

@haochenx `latest` 運用で特に問題無いです！

**Comment by kxc-waddlaw** [comment]
- #42 で対応完了なので close
